# andrew-mqtt-oauth-broker configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  config.yaml: |
    config:
      openid:
        connect_url: "https://login.students-epitech.ovh/realms/andrew/protocol/openid-connect/certs"
        client_id: "andrew-app"
        client_secret: ""
        subject_key: sub
        roles_key: roles
      roles:
        - name: device
          authorize_publish:
            - andrew/devices/*
          authorize_subscribe:
            - andrew/devices/*
        - name: device-manager
          authorize_publish: []
          authorize_subscribe:
            - andrew/devices/*
        - name: api
          authorize_publish:
            - andrew/devices/*
          authorize_subscribe: []
  config.schema.json: |-
    {
      "type": "object",
      "required": ["config"],
      "properties": {
        "config": {
          "required": ["openid", "roles"],
          "type": "object",
          "properties": {
            "openid": {
              "type": "object",
              "required": [
                "connect_url",
                "client_id",
                "client_secret",
                "subject_key",
                "roles_key"
              ],
              "properties": {
                "connect_url": {
                  "type": "string"
                },
                "client_id": {
                  "type": "string"
                },
                "client_secret": {
                  "type": "string"
                },
                "subject_key": {
                  "type": "string"
                },
                "roles_key": {
                  "type": "string"
                }
              }
            }
          },
          "roles": {
            "type": "object",
            "properties": {
              "config": {
                "type": "array",
                "items": {
                  "type": "object",
                  "required": ["name", "authorize_publish", "authorize_subscribe"],
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "authorize_publish": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "authorize_subscribe": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
---
# andrew-mqtt-oauth-broker STATEFULSET
apiVersion: apps/v1
kind: Statefulset
metadata:
  name: andrew-mqtt-oauth-broker-statefulset
  labels:
    tier: andrew-mqtt-oauth-broker
spec:
  serviceName: andrew-mqtt-oauth-broker-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      tier: andrew-mqtt-oauth-broker
  template:
    metadata:
      labels:
        tier: andrew-mqtt-oauth-broker
    spec:
      containers:
        - name: andrew-mqtt-oauth-broker
          image: antoineleguillou/andrew-mqtt-oauth-broker:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 350m
              memory: 450Mi
            requests:
              cpu: 250m
              memory: 250Mi
          ports:
            - containerPort: 8888
              name: ws
          volumeMounts:
            - name: app-config
              mountPath: /usr/share/app/config/
      restartPolicy: Always
      volumes:
        - name: app-config
          configMap:
            name: app-config
---
# andrew-mqtt-oauth-broker SERVICES
apiVersion: v1
kind: Service
metadata:
  name: andrew-mqtt-oauth-broker-service
spec:
  selector:
    tier: andrew-mqtt-oauth-broker
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      name: ws
