config:
  openid:
    connect_url: "https://login.students-epitech.ovh/realms/andrew/protocol/openid-connect/certs"
    client_id: "andrew-app"
    client_secret: ""
    subject_key: sub
    roles_key: roles
  internal_users: 
    - username: kafka-connect
      # test
      password: "$2b$10$aONHj.IkHgigW/Oum/LYPOy1yXxQobwznT.Ty3jN3tH6/vrqJF/9W"
  roles:
    - name: device
      authorize_publish:
        - $share/backend/vehicles/+/devices/+/cmd
      authorize_subscribe:
        - vehicles/+/devices/+/cmd
    - name: device-manager
      authorize_publish: []
      authorize_subscribe:
        - $share/backend/vehicles/+/devices/+/cmd
    - name: api
      authorize_publish:
        - vehicles/+/devices/+/cmd
      authorize_subscribe: []
