config:
  openid:
    connect_url: "https://login.students-epitech.ovh/realms/andrew/protocol/openid-connect/certs"
    client_id: "andrew-app"
    client_secret: ""
    subject_key: sub
    roles_key: roles
  internal_users: []
  acl:
    - name: device
      authorize_publish:
        - source/andrew-device/vehicles/+/devices/+/cmd/+
      authorize_subscribe:
        - source/andrew-device/vehicles/+/devices/+/cmd/+
  kafka:
    publish:
      connect_event:
        topic: andrew.devices.events
      disconnect_event:
        topic: andrew.devices.events
      client_events:
        - mqtt_topic: source/andrew-device/vehicles/+/devices/+/cmd/+
          topic: andrew.devices.events
