config:
  openid:
    connect_url: "https://login.students-epitech.ovh/realms/andrew/protocol/openid-connect/certs"
    client_id: "andrew-app"
    client_secret: ""
    subject_key: sub
    roles_key: roles
  internal_users:
    - username: api
      password: $2b$10$nHYAzkxFXDZ8R.Nm2y5bVu/BIsr6So0IQPwn21P8NQW9OnKMAe9Wy
  acl:
    - name: device
      authorize_publish:
        - source/andrew-device/vehicles/+/devices/+/cmd/+
      authorize_subscribe:
        - source/andrew-api/vehicles/+/devices/+/cmd/+
    - name: api
      authorize_publish:
        - source/andrew-api/vehicles/+/devices/+/cmd/+
        - source/frontend/users/#
      authorize_subscribe: []
    - name: user
      authorize_publish: []
      authorize_subscribe:
        - source/frontend/users/:id/#
    - name: supervisor
      authorize_publish: []
      authorize_subscribe:
        - source/frontend/supervisor/#
    - name: superadmin
      authorize_publish: []
      authorize_subscribe:
        - source/frontend/admin/#
        - source/frontend/supervisor/#
  kafka:
    publish:
      connect_event:
        topic: andrew-device-metrics
      disconnect_event:
        topic: andrew-device-metrics
      client_events:
        - mqtt_topic: source/andrew-device/vehicles/+/devices/+/cmd/+
          topic: andrew-device-metrics
