config:
  openid:
    connect_url: "https://login.students-epitech.ovh/realms/andrew/protocol/openid-connect/certs"
    client_id: "andrew-app"
    client_secret: ""
    subject_key: sub
    roles_key: roles
  roles:
    - name: device
      authorize_publish:
        - source/andrew-device/vehicles/+/devices/+/cmd/+
      authorize_subscribe:
        - source/andrew-device/vehicles/+/devices/+/cmd/+
    - name: device-manager
      authorize_publish: []
      authorize_subscribe:
        - source/andrew-device/vehicles/+/devices/+/cmd/+
    - name: api
      authorize_publish:
        - source/andrew-device/vehicles/+/devices/+/cmd/+
      authorize_subscribe: []
