name: Docker Image build and push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.NPM_PRIVATE_PACKAGE_SSH_PRIVATE_KEY }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: antoineleguillou/andrew-mqtt-oauth-broker
          tags: |
            type=raw,enable=true,priority=200,prefix={{ date 'YYYY-MM-DD' }},suffix=.${{ github.run_number }},value=

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
